# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

defaults: &defaults
  twitter_app:
    consumer_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
    consumer_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
    token_key: <%= ENV["TWITTER_TOKEN_KEY"] %>
    token_secret: <%= ENV["TWITTER_TOKEN_SECRET"] %>

development:
  secret_key_base: b3685f68a0163bdb2d0ec67e5ae9e5d3bad3efa24d3b706ac99055a4f6b6be71e3a459a742a9990adbb3b3e4ee897527df8bf6a127a9b4f04a19c90ec5a635eb
  <<: *defaults

test:
  secret_key_base: 9c27c078b6dc3b52bd0d4caad222c6710b19c0100e65b1a5b8b9b6a8e4bb699467c6b7b8f55b777aa70aaf5efce8e70db1a23b5bdaa5676978d014b7fec122ee
  <<: *defaults

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  <<: *defaults
